// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LastReport() {
  return window['go']['main']['PoolCensusApp']['LastReport']();
}

export function StartScan(arg1) {
  return window['go']['main']['PoolCensusApp']['StartScan'](arg1);
}
