// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LastReport():Promise<main.dashboardView>;

export function StartScan(arg1:number):Promise<main.dashboardView>;
